apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: git-clone-pipeline-annotator-run-
spec:
  pipelineRef:
    name: git-clone-pipeline
  params:
    - name: repo-url
      value: https://github.com/xfolka/napari-cci-annotator.git
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: shared-build-data-pvc
      subPath: annotator

      # volumeClaimTemplate:
      #   spec:
      #     accessModes: [ "ReadWriteOnce" ]
      #     resources:
      #       requests:
      #         storage: 1Gi
